apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: streamflow-risk
  namespace: epic-ai
  annotations:
    serving.kserve.io/s3-endpoint: "http://$(BUCKET_HOST):$(BUCKET_PORT)"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-secret-name: "kserve-s3-creds"
spec:
  predictor:
    sklearn:
      storageUri: s3://epic-demo-odf/models/streamflow_risk/latest/
      resources:
        requests: {cpu: "250m", memory: "512Mi"}
        limits: {cpu: "1", memory: "1Gi"}
